#! /usr/bin/python
# -*- coding: utf-8 -*-

import weibo
APP_KEY = '3896940168'
APP_SECRET = '38a77dde5d775310c8eb1215cbbf78ab'
CALL_BACK = 'http://hao.360.cn/?wd_xp1'#返回页网址

def run():
	client = weibo.APIClient(APP_KEY, APP_SECRET, CALL_BACK)
	auth_url = client.get_authorize_url()
	print "auth_url : " + auth_url
	code = raw_input("input the retured code : ")
	#通过该code获取access_token，r是返回的授权结果
	r = client.request_access_token(code)
	client.set_access_token(r.access_token, r.expires_in)

	while True:
		print "Ready! Do you want to send a new weibo?(y/n)"#判断是否要继续执行下去
		choice = raw_input()
		if choice == 'y' or choice == 'Y':
			content = raw_input('input the your new weibo content : ')
			if content:
				client.statuses.update.post(status=content)
				print "Send succesfully!"
				break;
			else:
				print "Error! Empty content!"
		if choice == 'n' or choice == 'N':
			break

if __name__ == "__main__":
	run()
